### PR TITLE
Terminal usage enhancements.

### PR DESCRIPTION
**Pull request by dchertousov**
- Throwing error when terminal is busy.
- Auto closing connection on exit whenever possible

### CODE REVIEW

**Comment by dchertousov** [comment]
Closes #61

**Comment by dchertousov** [comment]
@shmuga please review

**Comment by shmuga** [comment]
This one LGTM. 
Are you planning to add tests to this Service? As it has pretty complex state it would be nice to test this state for errors.

**Comment by dchertousov** [comment]
Test will be provided with #59

**Comment by shmuga** [comment]
@dchertousov Awesome. So I'm closing this one.

**Pull request merged**
